Leave Domain Option Fix on Non-AD Bound Device
TheJumpCloud/jumpcloud-ADMU pull request #113
Opened 2024-03-13 22:39 UTC by kmaranionjc

## Issues
* [CUT-3871](https://jumpcloud.atlassian.net/browse/CUT-3871) - CUT-3871-NonAD-Bound-System-No-Leave-Domain-Option

## What does this solve?
Fixes issue with leave domain GUI checkbox and -leaveDomain parameter in terminal that still tries to leave domain even when device is not AD bound.
## Is there anything particularly tricky?
n/a
## How should this be tested?
GUI
1. Run the GUI on an AD bound device and non-ad bound device
2. Validate that the GUI checkbox is enabled on AD bound device and disabled on non-ad bound device
Terminal
1. Run Start-Migration AD bound device and non-ad bound device
2. Set `-leaveDomain $true` on a non-ad device, this should still run the migration but will not try to leave the domain. 
![image](https://github.com/TheJumpCloud/jumpcloud-ADMU/assets/97972790/3e4eeba1-1675-477a-9118-bdbbf9550ace)
3. Set `-leaveDomain $true` on a domain joined device. Validate that the device leave the domain.

2024-03-14 15:39 UTC, jworkmanjc requested changes
Tests in PR worked for me, I have one item I think we should address that just feels off to me with our changes to the displayed logs.

Leave domain w/ local AD:
![Screenshot 2024-03-14 at 9 13 13 AM](https://github.com/TheJumpCloud/jumpcloud-ADMU/assets/54448601/a4ad2012-fde8-46c4-8e3f-ad8928d6bc9c)

Migrate on a system not on domain:
![Screenshot 2024-03-14 at 9 26 58 AM](https://github.com/TheJumpCloud/jumpcloud-ADMU/assets/54448601/482841f7-f785-44b2-b3f5-c753fd15cefb)
![Screenshot 2024-03-14 at 9 28 21 AM](https://github.com/TheJumpCloud/jumpcloud-ADMU/assets/54448601/b890b95f-3c82-40a3-b24d-2b75a911f42a)

In both cases, after the log writes `Updating UWP Apps for new user` the logs display `AzureAD Status: YES | NO`. In my opinion we should replace this. If I leave a local domain then this line will always display `NO` which is of no use to me. This should display something like:

Domain Status:
EntraAD: TRUE | FALSE
OnPremAD: TRUE | FALSE

or nothing at all. I'm open to discussion though.

2024-03-14 15:39 UTC, jworkmanjc commented on jumpcloud-ADMU/Powershell/Start-Migration.ps1
> +                                Write-ToLog -Message:('Unable to leave domain, JumpCloud agent will not start until resolved') -Level:('Warn')
```suggestion
                                Write-ToLog -Message:('Unable to leave domain') -Level:('Warn')
```

2024-03-14 15:39 UTC, jworkmanjc commented on jumpcloud-ADMU/Powershell/Start-Migration.ps1
> +                                Write-ToLog -Message:('Unable to leave domain, JumpCloud agent will not start until resolved') -Level:('Warn')
```suggestion
                                Write-ToLog -Message:('Unable to leave domain') -Level:('Warn')
```

2024-03-14 15:39 UTC, jworkmanjc commented on jumpcloud-ADMU/Powershell/Start-Migration.ps1
> +                                Write-ToLog -Message:('Unable to leave domain, JumpCloud agent will not start until resolved') -Level:('Warn')
```suggestion
                                Write-ToLog -Message:('Unable to leave domain') -Level:('Warn')
```

2024-03-14 15:39 UTC, jworkmanjc commented on jumpcloud-ADMU/Powershell/Start-Migration.ps1
>                              Write-ToLog -Message:('Unable to leave domain, JumpCloud agent will not start until resolved') -Level:('Warn')
```suggestion
                            Write-ToLog -Message:('Unable to leave domain') -Level:('Warn')
```

2024-03-14 17:55 UTC, kmaranionjc commented
> Tests in PR worked for me, I have one item I think we should address that just feels off to me with our changes to the displayed logs.
> 
> Leave domain w/ local AD: ![Screenshot 2024-03-14 at 9 13 13 AM](https://private-user-images.githubusercontent.com/54448601/312901988-a4ad2012-fde8-46c4-8e3f-ad8928d6bc9c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MzkwMzIsIm5iZiI6MTcxMDQzODczMiwicGF0aCI6Ii81NDQ0ODYwMS8zMTI5MDE5ODgtYTRhZDIwMTItZmRlOC00NmM0LThlM2YtYWQ4OTI4ZDZiYzljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDE3NTIxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjYzA4MjFhZDVkY2Q5MmJhYzhhY2ZkNTI3ZDcxODk4MTQwYjhmZjBhMWE5ZmE1MDFhMmI3MDBmMDBiMDI2N2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Lfur4coIF9ubmQbvw77WFN8FpLYb10ecjpUTN_3dy-U)
> 
> Migrate on a system not on domain: ![Screenshot 2024-03-14 at 9 26 58 AM](https://private-user-images.githubusercontent.com/54448601/312902212-482841f7-f785-44b2-b3f5-c753fd15cefb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MzkwMzIsIm5iZiI6MTcxMDQzODczMiwicGF0aCI6Ii81NDQ0ODYwMS8zMTI5MDIyMTItNDgyODQxZjctZjc4NS00NGIyLWIzZjUtYzc1M2ZkMTVjZWZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDE3NTIxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1YjM3NzIzNTNkYzA5ZmEwODk3NjliODc1Mzc3YzFlZTVlNTEzYWJkYzU0MDFkYWE0NDI3MjNmNzMxN2MzNGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nP8lRzagxwuQAKW6SETOas5NN-S6_qU7HgJKGiK6D6Q) ![Screenshot 2024-03-14 at 9 28 21 AM](https://private-user-images.githubusercontent.com/54448601/312902254-b890b95f-3c82-40a3-b24d-2b75a911f42a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MzkwMzIsIm5iZiI6MTcxMDQzODczMiwicGF0aCI6Ii81NDQ0ODYwMS8zMTI5MDIyNTQtYjg5MGI5NWYtM2M4Mi00MGEzLWIyNGQtMmI3NWE5MTFmNDJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDE3NTIxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0MTVlMjliMGIyZjkzZDc1Zjc2YTc0OWJjMmRjNDg2OWIxYTUwNzZlYmQ5M2E3MjZlYTkyZGU4MDliMTBlNGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Sx204ANKh_DJg-XkFAJMKO97yV4CqrLaBSO6ZdIwoIo)
> 
> In both cases, after the log writes `Updating UWP Apps for new user` the logs display `AzureAD Status: YES | NO`. In my opinion we should replace this. If I leave a local domain then this line will always display `NO` which is of no use to me. This should display something like:
> 
> Domain Status: EntraAD: TRUE | FALSE OnPremAD: TRUE | FALSE
> 
> or nothing at all. I'm open to discussion though.

Eh, I think we can just remove it completely from verbose. If we are troubleshooting, we are going to refer to the logs anyways.

2024-03-14 20:59 UTC, jworkmanjc approved these changes
✅ awesome thank you for the changes

2024-03-15 19:17 UTC, gweinjc approved these changes

2024-03-15 21:44 UTC, merged