Remove 40 char API Key Validation (#145)
TheJumpCloud/jumpcloud-ADMU pull request #146
Opened 2024-11-07 19:58 UTC by kmaranionjc

* remove 40char api key validation

* fix migrate button

* changelog

## Issues
* [<jira-id>](https://jumpcloud.atlassian.net/browse/<jira-id>) - <jira-title>

## What does this solve?

## Is there anything particularly tricky?

## How should this be tested?

## Screenshots

2024-12-03 20:33 UTC, jworkmanjc requested changes
Two things to change, 

- Cleaning up the tests that we have skipped now
- Making that file useful for customers

- Migration of a user that has a local user account  ✅
- Migration of a user on an MTP Org ✅
- Migration of a user that fails a step after the "merge" step does not remove the local user account ✅. This shouldn't trigger because we are not failing any steps after the merge step at the moment but even if someone adds that now, I see that the migrated accounts is there, logging in shows the expected "completion" window and brings me into the new account.

2024-12-03 20:33 UTC, jworkmanjc commented on jumpcloud-ADMU/Exe/jcexe.md
I see why this is here. Let's make this useful and instead of having a blank file. Let's change it to a file called Readme.MD, and just have bit of text to say:

The latest version of the JumpCloud admu including exe files can be found on our releases page.

2024-12-03 20:33 UTC, jworkmanjc commented on jumpcloud-ADMU/Powershell/Tests/Build.Tests.ps1
I think you should make that change to the file in the exe directory, let's just remove this test, there's no reason to keep it now.

2024-12-03 21:54 UTC, gweinjc submitted a review, later dismissed
API key length changes appear to work.
Nice job!

2024-12-04 14:49 UTC, jworkmanjc approved these changes
Thanks for the changes, just little things to help customers or us next time we look at something and ask why is this skipped. Thank you!

2024-12-04 16:52 UTC, gweinjc approved these changes

2024-12-04 17:07 UTC, merged