Sa 3000 admu reverse
TheJumpCloud/jumpcloud-ADMU pull request #94
Opened 2023-07-24 14:44 UTC by kmaranionjc

## Issues
* [SA-3000](https://jumpcloud.atlassian.net/browse/SA-3000) - SA-3000-ADMU-Reverse

## What does this solve?
Admins will be able to reverse an ADMU migration with the form and through commands.
## Is there anything particularly tricky?
N/A
## How should this be tested?
Normal Migrated User (Non-UpdatedHomepath)

1. Select an already migrated user on the form, this should enable Reverse Migrate checkbox
2. Reverse migrate
3. Validate that the .dat file, registry, and login has been updated

Migrated User with Updated-Homepath

1. Select a migrated user that has it's homepath updated from Start-Migration
2. Reverse migrate
3. Validate that the .dat file, registry, and login has been updated
4. Validate the user folder name C:\Users\YOURUSER is updated to the backup previous ProfileImagePath

2023-07-24 17:34 UTC, jworkmanjc commented on ModuleChangelog.md
> +* Reverse Migration
This needs to be expanded on, even a brief description of what this allows you to do and what's required (i.e. 'Added an option to the GUI tool which allows users to undo a user migration (converts a migrated local account back to itss original AD account if possible).

2023-07-28 20:04 UTC, jworkmanjc requested changes
I need to still review the tests but there are a few changes to get you started

2023-07-31 20:45 UTC, kmaranionjc commented on jumpcloud-ADMU/Powershell/Reverse-Migrate.ps1
> +    # $CurrentProfileImagePath = Get-ItemPropertyValue -Path "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\ProfileList\$($SelectedUserSid)" -Name 'ProfileImagePath'
No, removing it since we are getting the value from Get-UserHiveFile function

2023-07-31 20:51 UTC, kmaranionjc commented on jumpcloud-ADMU/Powershell/Form.ps1
> +        #TODO:
Nope, removing

2024-05-09 15:01 UTC, closed without merging